steps:
  #Execute SonarCloud Scan test 6
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=sulprogteste','-Dsonar.projectKey=sulprogteste_projetoteste','-Dsonar.login=${_SONAR_TOKEN}','-Dsonar.qualitygate.wait=true','-Dsonar.qualitygate.timeout=300']
    
    #Run Software Composition Analysis (SCA security scan) using Snyk in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:monitor  
          mvn snyk:test  
    id: SCA Scan using Snyk in GCP DevSecOps Pipeline
    
